name: bibliteso
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: 
  flutter_bloc:
  equatable: 
  share_plus:
  flutter_shimmer:
  flutter_share:
  # UI widgets:
  font_awesome_flutter:
  auth_buttons: 
  # Firebase plugins:
  firebase_core:
  firebase_auth:
  flutterfire_ui:
  cloud_firestore:
  google_sign_in:
  image_picker:
  qr_code_scanner: 

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true